FROM golang:1.23-alpine AS builder

RUN apk add --no-cache gcc musl-dev linux-headers git make

RUN git clone https://github.com/primev/mev-commit.git /mev-commit
WORKDIR /mev-commit/cl

RUN go mod tidy
RUN go build -o snode ./cmd/singlenode/main.go

FROM alpine:latest

COPY --from=builder /mev-commit/cl/snode /usr/local/bin/

COPY entrypoint_snode.sh /entrypoint_snode.sh
RUN chmod +x /entrypoint_snode.sh

ENTRYPOINT ["/entrypoint_snode.sh"]
