FROM golang:1.23-alpine AS builder

RUN apk add --no-cache gcc musl-dev linux-headers git make curl

RUN git clone https://github.com/primev/mev-commit-go-ethereum.git /go-ethereum
WORKDIR /go-ethereum

RUN git checkout ms-timestamp
RUN make geth

FROM alpine:latest

RUN apk add --no-cache jq

COPY --from=builder /go-ethereum/build/bin/geth /usr/local/bin/

COPY genesis.json /genesis.json

RUN jq '.config.terminalTotalDifficulty = 0' /genesis.json > /genesis.json.tmp && mv /genesis.json.tmp /genesis.json

COPY entrypoint_newgeth.sh /entrypoint_newgeth.sh
RUN chmod +x /entrypoint_newgeth.sh

EXPOSE 8545

ENTRYPOINT ["/entrypoint_newgeth.sh"]
